### ISSUE TITLE
The response body of a base 64 request overlaps across the screen

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/cloudsdk-aws-rebuild-api#34]
On the swagger screen, open the post for /api/Rebuild/base64
With the key entered, select a pdf file and execute
Notice that the response overlaps the swagger frame.

**Comment by Diggers89** [comment]
Could you please provide a screenshot of what you are seeing, I am unable to replicate this

**Comment by NadHodeGW** [comment]
![base64request_response body overlap](https://user-images.githubusercontent.com/61200359/81827305-8e80dc80-9530-11ea-8f25-ed7f35f40846.png)

**Comment by Diggers89** [comment]
What browser are you using for this?

**Comment by NadHodeGW** [comment]
Chrome

**Comment by Diggers89** [comment]
Issue with Swagger UI, will need to wait for a fix:

https://github.com/swagger-api/swagger-ui/issues/5934
