### ISSUE TITLE
Provide information on the Content Management Flags to new users of GW

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/cloudsdk-aws-rebuild-api#36]
The Content Management Policy/ Flags are mentioned as included in the request body but no explanation is given for them & a user who has never tried GW before would not know what they are.

See post sections: 
/api/Rebuild 
/api/Rebuild/base64

**Comment by Diggers89** [comment]
Information can be found in the schema section:

![image](https://user-images.githubusercontent.com/9385215/81816177-e0226a80-9522-11ea-8281-e2a47fc951ec.png)

Is more information required? If so what information?

**Comment by lukeR4** [comment]
This is a non-issue. Closing after discussing with Nadege.
