### ISSUE TITLE
Processed files returned in application_octet-stream format

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/cloudsdk-aws-rebuild-api#39]
On the swagger post for endpoint /api/Rebuild/file
Add the api key & upload a file (clean.png) then execute
Download the processed file 
Notice the the type is not png & cant be opened

The way around is renaming it to clean.png

File sent
![Clean](https://user-images.githubusercontent.com/61200359/81939670-88e9cc00-95ee-11ea-8601-f4f8f17062f7.png)

File received:
![2020-05-14_14h26_24](https://user-images.githubusercontent.com/61200359/81940087-19c0a780-95ef-11ea-8df5-aade6a6121d4.png)

**Comment by lukeR4** [comment]
Investigate this. May fix if possible

**Comment by lukeR4** [comment]
@gw-sbirch

**Comment by NadHodeGW** [comment]
Using postman, the response returned is in base64 format: 
Example response for file 
![Clean](https://user-images.githubusercontent.com/61200359/81962920-53ec7200-960c-11ea-9718-cddcb945959d.png)

is

iVBORw0KGgoAAAANSUhEUgAAAAsAAAALBAMAAABbgmoVAAAAGFBMVEX///8AUq0AY8Y5nP+MjIyUzv/W7////87upOv2AAAAAXRSTlMAQObYZgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAACxIAAAsSAdLdfvwAAAAHdElNRQfTAQICGAfQ7PyOAAAANElEQVR42mNggAJGQUEQJSgoKADiKCkpAimhEqVAEOVoDKaUTUGUknIYUI5BKDRIAKEPDAC1oAUVPU2kXQAAAABJRU5ErkJggg==

**Comment by gw-sbirch** [comment]
Fix found, Enabling response header 'Access-Control-Expose-Headers' to the client allows swagger to display and use headers in the response part of the documentation. This means that the response will show all the headers returned to the client and the file name will be correct
