### ISSUE TITLE
Server response is undocumented for a supplied incorrect x api key

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/cloudsdk-aws-rebuild-api#42]
On any of the endpoint on the swagger page, enter a invalid x-api-key and process a request
Notice that the server response code is: "Undocumented" and message: "TypeError: Failed to fetch"

This is incorrect to the specified expected response below:
"403 | Forbidden - This typically occurs when the x-api-key is not supplied, or it is incorrect."

![2020-05-18_undocumentederror](https://user-images.githubusercontent.com/61200359/82187401-440eaf80-98e4-11ea-8cb6-0bf0ec04765c.png)

**Comment by gw-sbirch** [comment]
@NadHodeGW  This is a configuration problem. This is because cors was not enabled on 403 errors. I have done this through the gateway.
